#!/usr/bin/env ruby

# This script will install the native extension locally in a bundler-compatible way
# without one having to check in -> push -> bundle update constantly.
#
# When you run this, it will compile the extension, then copy the result it into the lib directory
# like a good gem.
#
# The only other thing you need to do is manually declare this gem to be the gem's local directory
# in the Gemfile of your Rails project.
#
# To include debug symbols, add the "debug" command line option. e.g. when vendored:
#   > vendor/gems/ruby-opencv/build debug
#
# To verify that debug symbols are included, check if readelf has any output:
#   > readelf --debug-dump=decodedline vendor/gems/extensions/x86_64-linux/2.1.0/ruby-opencv-0.0.13.20140330211753/opencv.so | head
#

require 'rubygems'
require 'fileutils'


# Make sure we're building against the correct OpenCV version
expected_opencv_version = '2.4.10'
opencv_core_library_path = '/usr/local/lib/libopencv_core.so'
opencv_core_lib = File.realpath(opencv_core_library_path)
unless opencv_core_lib.end_with?(expected_opencv_version)
  puts "ERROR: Installed opencv version is #{ opencv_core_lib.sub("#{ opencv_core_library_path }.", '') }, not #{ expected_opencv_version }"
  exit(1)
end

is_debug_mode = ARGV.first.to_s == 'debug'

# This file can be run from a dedicated ruby-opencv directory, or from a vendored directory. In the latter case, it's
# not necessary to build or install the gem itself, just the native extension
is_vendored = !Dir.pwd.end_with?('ruby-opencv')

if is_vendored
  require 'bundler'
  Bundler.setup(:default)
  gem_spec = Gem::Specification.find_by_name 'ruby-opencv'
  
  puts "=> Building native extensions #{ '(debug)' if is_debug_mode }"
  
  # Copied from Gem::Specification#build_extensions
  begin
    # We need to require things in $LOAD_PATH without looking for the
    # extension we are about to build.
    unresolved_deps = Gem::Specification.unresolved_deps.dup
    Gem::Specification.unresolved_deps.clear
  
    require 'rubygems/config_file'
    require 'rubygems/ext'
    require 'rubygems/user_interaction'
    
    Gem::DefaultUserInteraction.use_ui Gem::ConsoleUI.new do
      build_args = gem_spec.build_args
      build_args << '--enable-debug' if is_debug_mode
      
      builder = Gem::Ext::Builder.new gem_spec, build_args
      builder.build_extensions
    end
  end

  library_filename = if RUBY_PLATFORM =~ /darwin|mac os/
    'opencv.bundle'
  else
    'opencv.so'
  end

  puts "=> Copying #{ library_filename } to #{ gem_spec.extension_dir }"
  `cp #{ gem_spec.gem_dir }/lib/#{ library_filename } #{ gem_spec.extension_dir }/#{ library_filename }`
else
  target_gemset_name = 'bonz-imagetools'
  
  gem_spec_filename = 'ruby-opencv.gemspec'
  gem_spec_path = "#{ File.dirname(__FILE__) }/#{ gem_spec_filename }"
  gem_spec = Gem::Specification.load(gem_spec_path)
  gem_filename = "#{ gem_spec.name }-#{ gem_spec.version }.gem"

# Build the gem
  puts "=> Building #{ gem_spec_filename }"
  unless system("gem build #{ gem_spec_filename }")
    puts '=> Gem build failed'
    exit(1)
  end

# Install gem in target RVM gemset
  puts "=> Installing #{ gem_filename }"
  unless system("#{ ENV['rvm_path'] }/wrappers/ruby-#{ RUBY_VERSION }@#{ target_gemset_name }/gem install #{ gem_filename }")
    puts '=> Gem install failed'
    exit(1)
  end
end

puts '=> Done'
